### ISSUE TITLE
Pebble2

### ISSUE THREAD

**Issue by djmbritt** [pebble-hacks/pebble-compass#2]
Hi there, 

I just got the pebble2 and I was testing this app on it.
But I keep getting stuck in the configuration phase.
In the part where I need to do an intricate dance.

I am guessing you just still need to update the app for the new sdk?

I hope that you have time, and can eventually get to it.

**Comment by cpfair** [comment]
The Pebble 2 does not have a magnetometer.

**Comment by djmbritt** [comment]
I see that now, thanks.
That was not clear to me in the beginning.
